
/**
 * Type Definitions for ChatAi Application
 *
 * This file contains all TypeScript type definitions and interfaces
 * used throughout the ChatAi application for type safety and
 * better development experience.
 *
 * Exports:
 * - MessageRole: Enum for distinguishing between user and AI messages
 * - ChatMessageData: Interface for chat message objects
 */

/**
 * Enumeration for message roles in the chat
 *
 * Used to distinguish between messages sent by the user
 * and responses generated by the AI system.
 */
export enum MessageRole {
  /** Messages sent by the user */
  USER = 'user',
  /** Messages generated by the AI */
  AI = 'ai',
}

/**
 * Interface for chat message data structure
 *
 * Represents a single message in the chat conversation,
 * containing all necessary information for display and processing.
 */
export interface ChatMessageData {
  /** Unique identifier for the message (timestamp-based) */
  id: number;
  /** Role indicating whether message is from user or AI */
  role: MessageRole;
  /** The actual text content of the message */
  text: string;
  /** Timestamp when the message was created */
  timestamp: Date;
}
